### PR TITLE
Added `add` and `remove` commands

### PR DESCRIPTION
**Pull request by denysdovhan**
Don`t forget change yours README.md!

### CODE REVIEW

**Comment by ziyaddin** [comment]
There is some problem with merging. It say's "We can’t automatically merge this pull request.". What caused the problem? It finds some conflicts between commits.

**Comment by denysdovhan** [comment]
Ok, I`ll try resolve merge conflict.

**Comment by denysdovhan** [comment]
I have a message:
> "Only those with **write access** to this repository can merge pull requests."

Maybe this conflict you should decide.

**Comment by ziyaddin** [comment]
What if I change the code without pull request (manually)? There is still a conflict between two branches and I can't deal with it.

**Comment by denysdovhan** [comment]
Nope, just add my repo to your local repo:

```
git remote add denysdovhan git@github.com:denysdovhan/xampp-cli.git
```

Then you must fetch or pull changes and resolve conflict with any merge tool.

**Comment by ziyaddin** [comment]
Done!

**Comment by denysdovhan** [comment]
Nice work :+1:

**Comment by ziyaddin** [comment]
@denysdovhan I want to write a blog post about the project when I am available, will mention you

**Comment by denysdovhan** [comment]
You forger to change README.md.

> when I am available, will mention you

Okey, I'll be waiting.

**Comment by ziyaddin** [comment]
Yeah I will change now. Also one point:

> xampp-cli

I think it will be great if I change it to xampp, isn't it? Because typing `xampp` in terminal is more comfortable.

**Comment by denysdovhan** [comment]
But it is no **xampp** repo, it is repo for xampp cli tool. `installer` automaticly rename `xampp-cli` to `xampp` while installing.

**Comment by ziyaddin** [comment]
Yeah I got it. :+1:

**Pull request merged**
